name: break-a-scene5
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - accelerate=0.19.0
  - aiohttp=3.8.1
  - aiosignal=1.3.1
  - arrow-cpp=11.0.0
  - async-timeout=4.0.2
  - attrs=23.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - boost-cpp=1.70.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.5.7
  - cffi=1.15.0
  - click=8.1.3
  - colorama=0.4.6
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - dataclasses=0.8
  - datasets=2.12.0
  - dill=0.3.6
  - ffmpeg=4.3
  - filelock=3.12.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.5.0
  - future=0.18.3
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - grpc-cpp=1.46.1
  - huggingface_hub=0.15.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.2.10
  - libcurand=10.3.3.141
  - libcurl=7.88.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnghttp2=1.46.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpmath=1.3.0
  - multidict=6.0.2
  - multiprocess=0.70.14
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openssl=1.1.1w
  - orc=1.7.4
  - packaging=23.1
  - pandas=1.5.3
  - pip=23.0.1
  - protobuf=3.20.3
  - psutil=5.9.0
  - pyarrow=11.0.0
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-xxhash=2.0.2
  - python_abi=3.10
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.1
  - requests=2.31.0
  - sacremoses=master
  - setuptools=67.8.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - tokenizers=0.11.4
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm=4.65.0
  - transformers=4.28.1
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - urllib3=2.0.3
  - utf8proc=2.6.1
  - wheel=0.38.4
  - xxhash=0.8.0
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - cachetools==5.3.2
      - cchardet==2.1.7
      - certifi==2023.5.7
      - chardet==5.1.0
      - charset-normalizer==3.1.0
      - diffusers==0.12.1
      - google-auth==2.23.4
      - google-auth-oauthlib==1.1.0
      - grpcio==1.59.2
      - markdown==3.5.1
      - oauthlib==3.2.2
      - opencv-python==4.7.0.68
      - pillow==9.5.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - regex==2023.6.3
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - werkzeug==3.0.1
prefix: /hpc/home/rami.skaik/.conda/envs/break-a-scene3
